runtime: php55
api_version: 1

handlers:
- url: /(index\.(html|html|php))?
  script: index.php
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
# Serve php scripts.
- url: /(.+\.(php|htm|html))$
  script: \1
